#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StoreComparatorXamarin.Resource", IsApplication=true)]

namespace StoreComparatorXamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::StoreComparatorXamarin.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::StoreComparatorXamarin.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int addItemsToCompare = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int allItemsFromStoreListView = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int allItemsListView = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int btnAddItem = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int btnCompareChoosenItems = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int btnCompareStores = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int btn_addStore = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int btndone = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int button3 = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int currentStores = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int itemsToCompareList = 2131034120;
			
			// aapt resource value: 0x7f050011
			public const int storeListView = 2131034129;
			
			// aapt resource value: 0x7f050001
			public const int txtCategory = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int txtName = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int txtPrice = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int txtTotalPrice = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int txtWeight = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int txt_store_name = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_add_edit_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_all_items = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_compared_items = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_select_items_to_compare = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_select_stores = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_store = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainActivity = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int action_settings = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int btn_add_store = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int hello_world = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int title_activity_add_edit_item = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int title_activity_all_items = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int title_activity_compared_items = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int title_activity_select_items_to_compare = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int title_activity_select_stores = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int title_activity_store = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int txt_empty_store_name = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int txt_store_name = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
